'use client';
import React,{useState} from 'react';import Link from 'next/link';import {usePathname} from 'next/navigation';import {RoutineView} from '../../components/RoutineView';import {hub,useHub} from '../../lib/hub';import {AppFrame,LoadState,NoProfile,SampleNotice} from '../../components/HubFrames';import {ConfirmDialog} from '../../components/ConfirmDialog';
export default function RoutinePage(){
 const state=useHub('/profile'),catalog=useHub('/catalog');const [pending,setPending]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const p=state.data?.profile,results=usePathname().endsWith('/results');
 const optional=p?.routine.steps.filter((s:any)=>s.is_optional).length||0;
 const missing=p?['cleanser','moisturizer','sunscreen'].filter(slot=>!p.routine.steps.some((s:any)=>s.slot===slot)):[];
 async function simplify(){setBusy(true);setMessage('');try{await hub('/routine/simplify',{expected_revision:state.data?.revision??null});setPending(false);setMessage('Your simpler routine has been saved.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <AppFrame title={results?'Your Skin Match':'My Routine'}><LoadState {...state} retry={state.reload}/>{!state.loading&&!state.error&&(p?<>{results&&<p className="notice success" role="status">Your preferences are saved. Review the available matches below.</p>}{p.sample&&<SampleNotice/>}{missing.length>0&&<section className="notice"><h2 style={{fontSize:'1.2rem'}}>Some routine steps have no eligible match.</h2><p>Missing: {missing.join(', ')}. The catalog did not provide an eligible product for these steps. This is a partial routine.</p><Link className="text-link" href="/my-skin">Review your preferences</Link></section>}{catalog.error&&<p className="notice" role="alert">Product names could not load. <button className="text-button" onClick={catalog.reload}>Try again</button></p>}<div className="panel"><RoutineView routine={p.routine} productName={id=>catalog.data?.products.find((x:any)=>x.id===id)?.name||id.replace(/-/g,' ')}/></div><div className="actions">{optional>0&&<button className="button" disabled={busy} onClick={()=>setPending(true)}>Simplify my routine</button>}<Link className="button primary" href="/shop">Find an external retailer ↗</Link><Link className="text-link" href="/my-skin">Review my profile</Link></div>{optional===0&&<p className="muted">Your routine has no optional steps to remove.</p>}<ConfirmDialog open={pending} title="Save a simpler routine?" busy={busy} onCancel={()=>setPending(false)} onConfirm={simplify} confirmLabel="Save simpler routine"><p>This removes {optional} optional {optional===1?'step':'steps'} from your saved routine. Your skin preferences stay the same.</p></ConfirmDialog></>:<NoProfile/>)}{message&&<p role="status" className="notice">{message}</p>}</AppFrame>;}

