from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.colors import HexColor
import os

OUT=os.path.join("output","pdf","AP_World_History_Pre_1200_Study_Guide_and_Practice.pdf")
os.makedirs(os.path.dirname(OUT),exist_ok=True)
NAVY=HexColor("#17324D"); TEAL=HexColor("#1B7F8C"); GOLD=HexColor("#D9A441"); LIGHT=HexColor("#EFF5F7"); PALE=HexColor("#FFF8E8"); GRAY=HexColor("#5B6770")
s=getSampleStyleSheet()
s.add(ParagraphStyle(name="CoverTitle",parent=s["Title"],fontName="Helvetica-Bold",fontSize=24,leading=28,alignment=TA_CENTER,textColor=NAVY,spaceAfter=14))
s.add(ParagraphStyle(name="CoverSub",parent=s["Normal"],fontSize=11,leading=15,alignment=TA_CENTER,textColor=GRAY,spaceAfter=7))
s.add(ParagraphStyle(name="H1x",parent=s["Heading1"],fontName="Helvetica-Bold",fontSize=17,leading=21,textColor=NAVY,spaceBefore=8,spaceAfter=8,keepWithNext=True))
s.add(ParagraphStyle(name="H2x",parent=s["Heading2"],fontName="Helvetica-Bold",fontSize=12.5,leading=15,textColor=TEAL,spaceBefore=8,spaceAfter=4,keepWithNext=True))
s.add(ParagraphStyle(name="Bodyx",parent=s["BodyText"],fontSize=9.1,leading=12.1,spaceAfter=5))
s.add(ParagraphStyle(name="Smallx",parent=s["BodyText"],fontSize=7.8,leading=9.8,textColor=GRAY,spaceAfter=3))
s.add(ParagraphStyle(name="Qx",parent=s["BodyText"],fontSize=8.5,leading=10.8,spaceAfter=3))
s.add(ParagraphStyle(name="Stim",parent=s["BodyText"],fontSize=8.2,leading=10.5,leftIndent=9,rightIndent=9,borderColor=TEAL,borderWidth=.7,borderPadding=6,backColor=LIGHT,spaceBefore=3,spaceAfter=5))
s.add(ParagraphStyle(name="Answer",parent=s["BodyText"],fontSize=8,leading=10,spaceAfter=2))
def P(x,st="Bodyx"): return Paragraph(x,s[st])
def bullet(x): return P("&bull; "+x)
def box(title,text,bg=LIGHT):
    t=Table([[P("<b>"+title+"</b>","H2x")],[P(text)]],colWidths=[6.55*inch])
    t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),bg),("BOX",(0,0),(-1,-1),.7,TEAL),("LEFTPADDING",(0,0),(-1,-1),8),("RIGHTPADDING",(0,0),(-1,-1),8),("TOPPADDING",(0,0),(-1,-1),5),("BOTTOMPADDING",(0,0),(-1,-1),5)]))
    return t
def footer(c,d):
    c.saveState(); c.setStrokeColor(HexColor("#C9D5DB")); c.setLineWidth(.4); c.line(.65*inch,.48*inch,7.85*inch,.48*inch)
    c.setFont("Helvetica",7.5); c.setFillColor(GRAY); c.drawString(.65*inch,.3*inch,"AP World History: Modern | Unofficial materials based on AMSCO excerpt pp. 33-64"); c.drawRightString(7.85*inch,.3*inch,str(d.page)); c.restoreState()
story=[Spacer(1,.75*inch),P("AP World History: Modern","CoverSub"),P("Comprehensive Study Guide + Practice Materials","CoverTitle"),P("Focus: Historical thinking skills and world history before 1200 C.E.","CoverSub"),Spacer(1,.2*inch),box("Included","Complete review guide; 20-question AP-style practice test; separate 20-question AP-style practice quiz; answer keys, rationales, and final checklist.",PALE),Spacer(1,.3*inch),P("<b>Source basis:</b> AMSCO AP World History excerpt, supplied PDF pages 33-64. The excerpt covers DBQ/LEQ skills, review planning, human development, early agriculture, early civilizations, belief systems, classical empires, postclassical societies, exchange networks, and the world in 1200.","Smallx"),P("<b>Important:</b> These are original, unofficial practice materials designed to exercise College Board-style historical reasoning and stimulus analysis.","Smallx"),PageBreak()]
story += [P("Part I. How to Think Like an AP Historian","H1x"),P("AP World History rewards students who use evidence to explain developments, not merely recall names and dates. For every topic, identify the development, locate it in time and place, explain causes and effects, compare it with another society, and evaluate the evidence supporting a claim.")]
for a,b in [("1. Developments and Processes","Identify and explain patterns, turning points, continuities, and consequences across time."),("2. Sourcing and Situation","Analyze point of view, purpose, audience, and historical situation. Explain how context shapes what a source reveals or limits."),("3. Claims and Evidence in Sources","Identify a source claim and explain how specific evidence supports, qualifies, or challenges it."),("4. Contextualization","Connect a topic to broader political, economic, social, cultural, environmental, or technological developments."),("5. Making Connections","Use comparison, causation, or continuity and change over time to build an explanation."),("6. Argumentation","Develop a defensible claim, organize relevant evidence, and demonstrate nuance through multiple variables or counterevidence.")]:
    story += [P(a,"H2x"),P(b)]
story += [box("MCQ habits","Read the stimulus for authorship, date, place, purpose, and central claim. Then eliminate choices that are outside the time period, geographically misplaced, too broad, or true but not responsive."),PageBreak(),P("Part II. Writing and Review Skills","H1x"),P("The excerpt emphasizes that strong historical writing is planned: make a claim, place it in context, select evidence, and explain why the evidence matters."),P("DBQ checklist","H2x")]
for x in ["Read the prompt twice; underline the task verb and circle content targets.","Write a thesis that takes a position and previews a line of reasoning.","Group documents by argument, looking for corroboration and contradiction.","Use documents by explaining their content, not by inserting quotations without analysis.","Source at least three documents using point of view, purpose, audience, or historical situation.","Add one specific, relevant piece of evidence beyond the documents.","Demonstrate complexity through multiple causes, similarities and differences, continuity and change, or qualifying evidence."]: story += [bullet(x)]
story += [P("LEQ checklist","H2x")]
for x in ["Identify the topic and reasoning process: comparison, causation, or continuity and change.","Spend a few minutes organizing evidence in an outline or table.","State a defensible thesis in one place, usually the introduction.","Use specific evidence and explain how it supports the claim.","Stay focused on the prompt; information alone is not analysis."]: story += [bullet(x)]
story += [P("Command words","H2x")]
data=[[P("<b>Verb</b>","Smallx"),P("<b>What it asks you to do</b>","Smallx")],[P("Compare","Smallx"),P("Explain meaningful similarities and/or differences.","Smallx")],[P("Describe","Smallx"),P("Provide relevant characteristics.","Smallx")],[P("Explain","Smallx"),P("Show how or why a relationship exists.","Smallx")],[P("Evaluate","Smallx"),P("Judge significance, importance, quality, or accuracy using evidence.","Smallx")],[P("Analyze","Smallx"),P("Break a development into parts and explain relationships among them.","Smallx")]]
t=Table(data,colWidths=[1.25*inch,5.3*inch]); t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),NAVY),("TEXTCOLOR",(0,0),(-1,0),colors.white),("GRID",(0,0),(-1,-1),.35,HexColor("#B7C7CD")),("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),6),("RIGHTPADDING",(0,0),(-1,-1),6),("TOPPADDING",(0,0),(-1,-1),5),("BOTTOMPADDING",(0,0),(-1,-1),5)])); story += [t,PageBreak()]
story += [P("Part III. Comprehensive Content Guide: Before 1200 C.E.","H1x"),P("Use this as a connected narrative. The high-yield pattern is that environment and technology shaped food production; surplus supported cities and states; states and networks spread ideas, goods, and disease.")]
sections=[
("A. Human Development and Agriculture",["Modern humans emerged in East Africa and migrated across the world. Paleolithic communities relied mainly on hunting, gathering, and mobility; mobility supported adaptation but limited surplus accumulation.","Beginning around 10,000 years ago, warming climates supported domestication of plants and animals. Surplus enabled population growth, permanent settlements, labor specialization, social stratification, organized religion, and complex government.","The shift was not universal or instantaneous. Foraging continued in many regions, while agriculture also created disease, environmental strain, and inequality."]),
("B. Early Civilizations and State Formation",["Mesopotamia developed between the Tigris and Euphrates. City-states, irrigation, writing, law codes, and hierarchy reflected the need to coordinate agriculture and defend territory.","Egypt relied on the Nile. Regular flooding supported centralized rule under pharaohs; monumental architecture expressed state power. Egyptian women had comparatively strong property and legal rights.","The Indus civilization developed planned cities such as Harappa and Mohenjo-Daro and engaged in long-distance trade. Early China developed along the Huang He; the Zhou Mandate of Heaven linked political legitimacy to moral rule.","The Americas developed independently. Olmec, Chavin, and later Maya societies connected agriculture, religious authority, urban centers, and regional exchange."]),
("C. Belief Systems and Cultural Change",["Hindu traditions emphasized dharma, karma, samsara, and moksha; social roles became associated with varna and jati.","Judaism developed as monotheism centered on a covenant between one God and the Hebrew people.","Buddhism began with Siddhartha Gautama. The Four Noble Truths and Eightfold Path offered a route beyond suffering; merchants, missionaries, and states helped spread it.","Confucianism emphasized ethical behavior, filial piety, education, and social harmony. Daoism stressed harmony with the Dao and alignment with nature.","Christianity emerged from the Jewish context of Roman-ruled Southwest Asia. Missionary activity and later Roman imperial support helped it spread across the Mediterranean."]),
("D. Classical Empires, c. 600 B.C.E.-600 C.E.",["Persia used satrapies, roads, tribute, and tolerance of local customs to govern a diverse land empire.","Greek poleis varied: Athens developed participatory democracy for male citizens, while Sparta emphasized military discipline. Greek culture spread through colonization and conquest.","Rome expanded through military organization, citizenship, infrastructure, and law. Its patriarchal society still granted many Roman women more property and divorce rights than Greek women.","The Mauryan Empire unified much of South Asia. Ashoka promoted Buddhism and ethical governance after conquest; Gupta India is associated with mathematics, science, and trade.","Qin centralization and Han expansion created a durable imperial model in China, supported by bureaucracy, Confucian ideals, and infrastructure.","Classical empires shared centralization, taxation, hierarchy, military power, and exchange. Decline often involved overexpansion, internal conflict, economic strain, invasion, or environmental pressure."]),
("E. Exchange and Postclassical States, c. 600-1200",["The Silk Roads connected East Asia, Central Asia, South Asia, the Middle East, and Europe. Luxury goods, technologies, religions, and disease moved along them.","Indian Ocean trade relied on monsoon winds, maritime knowledge, and port cities. Textiles, spices, metals, languages, and religions circulated across East Africa, Arabia, South Asia, and Southeast Asia.","Trans-Saharan exchange expanded with camels and saddles. Ghana benefited by taxing gold-salt exchange and controlling routes.","Islam emerged in Arabia and spread through conquest, trade, migration, and missionary activity. Sunni-Shi'a divisions originated in disagreement over legitimate leadership after Muhammad.","The Sui reunified China and built the Grand Canal. Tang and Song China supported commercial growth, cities, tributary relations, and technological innovation.","In Europe, feudal and manorial systems organized life after Rome. In the Americas, Maya regional decline, Mississippian Cahokia, and Andean states show diverse paths to complexity."]),
("F. The World in 1200",["By 1200, Afro-Eurasia was increasingly connected through trade routes and expanding states. Islamic empires, Byzantium, China, South Asian states, and African kingdoms formed overlapping zones of exchange.","Regional differences remained important in institutions, belief systems, gender systems, ecology, and technology. The central pattern is interaction: states supported exchange, exchange spread ideas and pathogens, and technology changed the scale of political and economic life."])]
for title,ps in sections:
    story += [P(title,"H2x")]+[P(x) for x in ps]
story += [P("Comparison matrix","H2x")]
matrix=[[P("<b>Theme</b>","Smallx"),P("<b>Examples</b>","Smallx"),P("<b>Question to ask</b>","Smallx")],[P("Government","Smallx"),P("Mandate of Heaven; satrapies; Roman citizenship; Chinese bureaucracy","Smallx"),P("How did rulers create legitimacy and manage diversity?","Smallx")],[P("Economy","Smallx"),P("Irrigation; Silk Roads; Indian Ocean; trans-Saharan routes","Smallx"),P("How did environment and technology shape exchange?","Smallx")],[P("Culture","Smallx"),P("Hinduism; Buddhism; Confucianism; Christianity; Islam","Smallx"),P("Why did some beliefs spread beyond their origins?","Smallx")],[P("Society","Smallx"),P("Patriarchy; varna; slavery; hierarchy","Smallx"),P("What changed and what persisted?","Smallx")],[P("Environment","Smallx"),P("Nile; Huang He; monsoons; Sahara; urban stress","Smallx"),P("How did societies adapt to or intensify conditions?","Smallx")]]
t=Table(matrix,colWidths=[1.05*inch,2.8*inch,2.7*inch]); t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),NAVY),("TEXTCOLOR",(0,0),(-1,0),colors.white),("GRID",(0,0),(-1,-1),.35,HexColor("#B7C7CD")),("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),5),("RIGHTPADDING",(0,0),(-1,-1),5),("TOPPADDING",(0,0),(-1,-1),5),("BOTTOMPADDING",(0,0),(-1,-1),5)])); story += [t,PageBreak()]
def add_set(title,items):
    global story
    story += [P(title,"H1x"),P("Suggested timing: 25 minutes. Original, unofficial questions modeled on stimulus-based AP historical reasoning.","Smallx")]
    for n,stim,q,opts,ans,rat in items:
        if stim: story += [P(stim,"Stim")]
        story += [P(f"<b>{n}. {q}</b>","Qx")]+[P(o,"Qx") for o in opts]
    story += [PageBreak(),P(title+" - Answer Key and Rationales","H1x")]
    for n,stim,q,opts,ans,rat in items: story += [P(f"<b>{n}. {ans}</b> - {rat}","Answer")]
A=[
(1,"A historian writes: \"Agriculture created the material conditions for cities and states, but it also intensified disease, labor demands, and inequality.\"","The development described most directly contributed to which change?",["A. Decline of permanent settlements","B. Labor specialization and social stratification","C. End of religious authority","D. Elimination of interregional trade"],"B","Surplus supported specialists, cities, hierarchy, and states."),
(2,"","Which evidence best supports the historian's qualification?",["A. Irrigation required coordinated labor and maintenance","B. Foragers moved seasonally","C. Monumental architecture expressed royal authority","D. Camel saddles increased desert travel"],"A","Irrigation shows food production coupled with labor demands and organization."),
(3,"","The argument is best placed in the context of which broader process?",["A. Industrialization","B. Neolithic domestication and settlement","C. Atlantic revolutions","D. Cold War decolonization"],"B","The stimulus concerns the Agricultural Revolution."),
(4,"A Persian royal inscription praises a king for ruling many peoples, maintaining roads, collecting tribute, and allowing local customs.","The policy described most likely helped Persia do which?",["A. Govern a large diverse land empire","B. Replace taxation with barter","C. End expansion","D. Establish direct democracy"],"A","Administrative flexibility and infrastructure supported integration."),
(5,"","The source's purpose most likely limits it because it",["A. ignores Persian roads","B. exaggerates the ruler's success and benevolence","C. was written by a conquered Greek","D. focuses on Indian Ocean merchants"],"B","Royal inscriptions are legitimizing sources."),
(6,"","Which development provides the strongest comparison?",["A. Roman citizenship integrated conquered peoples","B. Maya drought ended all urban life","C. Greek poleis rejected written laws","D. Paleolithic groups abandoned mobility"],"A","Rome also used institutions to manage diversity."),
(7,"A Buddhist teaching states that suffering arises from craving and disciplined conduct, meditation, and wisdom lead to liberation.","The teaching most directly challenged which assumption?",["A. Spiritual status was permanently inherited","B. Merchants could travel by sea","C. Rulers needed armies","D. Farmers needed irrigation"],"A","Buddhism offered a path beyond inherited status."),
(8,"","Which factor best explains the teaching's spread?",["A. Merchant networks and state patronage","B. Collapse of all empires","C. Printing press","D. European colonization"],"A","Merchants, missionaries, and rulers spread Buddhism."),
(9,"","Which development similarly linked ethics to political order?",["A. Confucian conduct and hierarchy","B. Camel transport","C. Roman persecution","D. Indus drainage"],"A","Confucianism connected ethics, society, and governance."),
(10,"A table lists Mauryan Ashoka and Buddhism; Han bureaucracy and Confucian ideals; Rome's citizenship, law, and roads; Gupta mathematics and trade.","The table best supports which conclusion?",["A. Classical states used one model","B. State formation and culture were interconnected","C. Trade disappeared","D. Religion had no political relation"],"B","The examples show varied institutions alongside cultural development."),
(11,"","Which development enabled these states to project power over distance?",["A. Administration and infrastructure","B. Disappearance of cities","C. Hunting alone","D. Isolation"],"A","Bureaucracy, roads, law, and taxation supported expansion."),
(12,"","The table would be most useful for which question?",["A. Compare political and cultural strategies","B. Why agriculture began in the Middle East","C. Industrial labor","D. Cold War alliances"],"A","Its organization invites comparison."),
(13,"An East African merchant records ships timing departures to seasonal winds and visiting multilingual ports.","The environmental factor most directly supporting the trade was",["A. Monsoon patterns","B. Nile flooding","C. Himalayan isolation","D. Sahara drought"],"A","Indian Ocean sailors used seasonal monsoons."),
(14,"","Which consequence most likely followed?",["A. Cultural diffusion in port cities","B. Isolation of East Africa","C. End of commerce","D. Elimination of local authority"],"A","Ports became contact zones."),
(15,"","Which evidence best demonstrates the network's scale?",["A. Muslim merchant communities in coastal South and Southeast Asia","B. Roman divorce rights","C. Maya calendars","D. Zhou claims"],"A","Diasporic communities show sustained exchange."),
(16,"A passage states that Han decline brought disunity; Sui reunified China; Tang and Song supported growth, commerce, and tributary relations.","The passage best illustrates",["A. Cycles of fragmentation and reunification","B. Permanent Chinese decline","C. Replacement of agriculture","D. End of state trade"],"A","It describes turmoil followed by reunification and growth."),
(17,"","The Grand Canal most directly affected China by",["A. Linking agricultural regions and supporting distribution","B. Preventing migration","C. Ending tribute","D. Isolating markets"],"A","It connected grain regions and strengthened administration."),
(18,"","The tributary system reflects which broader pattern?",["A. A powerful state used diplomacy and trade to structure relations","B. All neighbors were annexed","C. Trade was unrelated to hierarchy","D. China rejected influence"],"A","Tribute and trade were linked to Chinese centrality."),
(19,"A historian argues the postclassical era recombined older traditions through wider networks, producing new formations.","Which evidence best supports the claim?",["A. Islam spread while reshaping local traditions","B. All states copied Rome","C. Routes stopped carrying religion","D. Cities disappeared"],"A","Expansion and adaptation show recombination."),
(20,"","Which development most complicates the claim that the era was merely recovery?",["A. New trans-Saharan and Indian Ocean centers gained wealth","B. Classical empires declined","C. Han turmoil occurred","D. Maya faced stress"],"A","New centers indicate transformation, not only restoration.")]

B=[
(1,"An archaeologist compares planned Indus cities, Mesopotamian city-states, and Nile settlements; all depended on surplus, but layouts and political evidence differ.","Which claim is best supported?",["A. Cities had identical institutions","B. Surplus supported urbanization while allowing variation","C. Urbanization ended adaptation","D. Indus and Mesopotamia had no contact"],"B","The comparison identifies a shared basis without erasing differences."),
(2,"","Which question best evaluates the political evidence?",["A. How reliable are archaeological remains for identifying rulers?","B. Did later empires use gunpowder?","C. How did Atlantic slavery change labor?","D. Why did industrialization begin in Britain?"],"A","It directly addresses evidence and source limits."),
(3,"A Confucian scholar argues stability depends on virtuous rulers and subjects fulfilling duties.","The argument reflects the impact of",["A. Confucianism on Chinese political thought","B. Buddhism on Roman law","C. Christianity on Maya calendars","D. Daoism on Persian satrapies"],"A","The claim links ethics, hierarchy, and government."),
(4,"","Which development increased the scholar's influence?",["A. Educated officials and bureaucracy","B. Abandonment of agriculture","C. Greek conquest of East Asia","D. End of maritime exchange"],"A","Education and bureaucracy supported Confucian ideals."),
(5,"A Roman author calls Christians disruptive because they refuse sacrifice to Roman gods. Later policy tolerates and supports Christianity.","The criticism shows that",["A. Religious practice could challenge political expectations","B. Rome had no religion","C. Christianity began in East Asia","D. All Romans were monotheists"],"A","Civic religious practice had political meaning."),
(6,"","The later policy change illustrates that",["A. States may adopt formerly marginal beliefs for political reasons","B. Persecution always destroys religions","C. Religions spread only by conquest","D. Rome rejected cultural change"],"A","State policy can change with political conditions."),
(7,"A map identifies Silk Roads, Indian Ocean routes, and trans-Saharan routes.","Which factor is most closely associated with Indian Ocean routes?",["A. Monsoon knowledge","B. Chariot warfare","C. Nile cataracts","D. Roman concrete"],"A","Monsoons enabled predictable sailing."),
(8,"","Which factor increased trans-Saharan exchange?",["A. Camel saddles and caravans","B. Gunpowder","C. Steam engines","D. Printing presses"],"A","Camel technology made crossings practical."),
(9,"An essay claims all empires declined for weak leadership. A reviewer cites overexpansion, conflict, economic strain, invasion, and environmental stress.","The reviewer's response demonstrates",["A. Complexity through multiple causation","B. Simple narration","C. Audience analysis only","D. Memorization"],"A","It rejects a single cause."),
(10,"","Which example supports the critique?",["A. Rome faced internal instability and external pressure while governing vast territory","B. Agriculture preceded classical empires","C. Confucius valued education","D. Merchants used winds"],"A","Rome illustrates interacting causes."),
(11,"A Ghanaian ruler taxes gold moving north and salt moving south; Muslim merchants participate.","What most directly explains Ghana's wealth?",["A. State control and taxation of exchange","B. Isolation from merchants","C. Roman roads","D. Decline of camels"],"A","Ghana profited by taxing and regulating routes."),
(12,"","The stimulus demonstrates trade networks",["A. Could strengthen states and spread culture","B. Always weakened governments","C. Were limited to Chinese luxuries","D. Required one religion"],"A","Revenue and cultural interaction grew together."),
(13,"A comparison notes Greek women generally lacked rights available to many Roman women, while both societies were patriarchal.","Which conclusion is most defensible?",["A. Shared patriarchy can contain regional differences","B. Rome was egalitarian","C. Systems were identical","D. Women controlled governments"],"A","The evidence supports continuity and difference."),
(14,"","Which evidence would strengthen the comparison?",["A. Legal rights, property, and family roles in both societies","B. Roman military victories only","C. Chinese dynasty dates","D. Monsoon winds"],"A","Comparable categories make comparison rigorous."),
(15,"A textbook states some Maya cities declined because degradation, drought, and warfare interacted, although some cities remained occupied.","The phrase \"although some cities remained\" primarily",["A. Qualifies an overgeneralization","B. Establishes one cause","C. Denies environmental change","D. Compares Maya and Roman law"],"A","It emphasizes regional variation."),
(16,"","Which process is similar?",["A. Classical decline varied by region","B. Agriculture began everywhere at once","C. Buddhism began with one teacher","D. Persia used satrapies"],"A","Both emphasize uneven change."),
(17,"A Tang official calls China the Middle Kingdom and expects tribute in exchange for trade privileges.","The policy reflects",["A. Hierarchical diplomacy centered on China","B. Equality among states","C. Rejection of commerce","D. Roman citizenship"],"A","Tribute and commerce were linked to status."),
(18,"","Which development contextualizes this policy?",["A. Reunification and growth after Sui and during Tang","B. Paleolithic migration","C. Atlantic empires","D. Industrial Revolution"],"A","It fits revival of centralized Chinese power."),
(19,"A student organizes evidence under shared features, regional differences, and evidence complicating the claim.","This organization supports",["A. A complex historical argument","B. Pure description","C. A source-free response","D. Chronology only"],"A","It makes comparison and qualification visible."),
(20,"","Which practice completes the method?",["A. Explain how evidence supports, modifies, or limits the thesis","B. Quote at length without analysis","C. Use document order only","D. Remove contradictions"],"A","Argument requires reasoning about all relevant evidence.")]

add_set("Part IV. Practice Test A - 20 AP-Style Multiple-Choice Questions",A)
add_set("Part V. Practice Quiz B - 20 AP-Style Multiple-Choice Questions",B)
story += [PageBreak(),P("Part VI. Final Review Checklist","H1x"),P("Before the assessment, you should be able to do each of the following without notes:")]
for x in ["Explain why agriculture created both new possibilities and new inequalities.","Compare Mesopotamia, Egypt, the Indus, and early China in environment, government, and society.","Explain the core ideas and spread mechanisms of Hinduism, Judaism, Buddhism, Confucianism, Daoism, Christianity, and Islam.","Compare Persia, Greece, Rome, Maurya/Gupta India, and Qin/Han China.","Explain how Silk Roads, Indian Ocean routes, and trans-Saharan routes depended on technology and environment.","Describe how trade spread religions, languages, technologies, and disease.","Use causation to explain the rise and decline of states.","Use comparison to distinguish shared patterns from regional differences.","Use sourcing language: point of view, purpose, audience, historical situation, and limitation.","Write a thesis that answers a prompt and establishes a line of reasoning.","Eliminate MCQ choices that are chronologically, geographically, or logically mismatched."]: story += [P("[ ] "+x)]
story += [Spacer(1,8),box("One-minute self-test","Can you explain one development using all six lenses: process, sourcing, evidence, context, connections, and argumentation?",PALE),Spacer(1,10),P("<b>Reference note:</b> Content was synthesized from the supplied AMSCO excerpt. Current AP-style alignment was checked against College Board AP World History: Modern materials on AP Central as of September 2026.","Smallx")]
SimpleDocTemplate(OUT,pagesize=letter,rightMargin=.65*inch,leftMargin=.65*inch,topMargin=.6*inch,bottomMargin=.65*inch,title="AP World History Study Guide and Practice Materials").build(story,onFirstPage=footer,onLaterPages=footer)
print(OUT)

