import Link from 'next/link';
import {notFound} from 'next/navigation';
const pages:Record<string,{title:string;intro:string;heading:string;body:string;href:string;cta:string}>={
 company:{title:'Skincare, thoughtfully connected.',intro:'MGT Skin Care brings skin preferences, routine planning and product guidance into one workspace.',heading:'Our starting point is you.',body:'The portal is in development. Verified company details, contact information and affiliations will be published before launch.',href:'/trust',cta:'Understand our approach'},
 trust:{title:'Understand your guidance.',intro:'Your preferences come first. Recommendations should explain their reasoning and leave the final choice with you.',heading:'A clear boundary for AI.',body:'The portal is being built for cosmetic guidance, not diagnosis or treatment. Ingredient review, account protection and AI services still require launch validation. Retail purchases take place on external websites; each vendor of record handles billing, shipping and returns.',href:'/skin-match',cta:'Explore Skin Match'},
 learn:{title:'Get to know your workspace.',intro:'Start with your preferences, explore your routine, and keep your choices connected.',heading:'Begin with Skin Match.',body:'Answer questions about your skin and goals. My Routine is where your morning and evening steps appear; My Skin is where you can review your profile. Reviewed educational articles will be added before launch.',href:'/skin-match',cta:'Start Skin Match'},
 support:{title:'A little help, when you need it.',intro:'Support will be available here when the portal launches.',heading:'Contact details are being finalized.',body:'No support email or response-time commitment has been published yet. For now, you can return to the application hub and explore the available screens.',href:'/',cta:'Back to applications'},
 privacy:{title:'Your information matters.',intro:'The final privacy notice will be published before account registration is enabled.',heading:'This is a development preview.',body:'Data handling, retention periods, service providers and your privacy rights must be confirmed in the final notice. Please use sample information while exploring this preview.',href:'/trust',cta:'View the current service boundaries'},
 terms:{title:'Clear terms, before you commit.',intro:'The final terms of service will be available before launch.',heading:'Purchases and subscriptions are not live.',body:'MGT provides discovery and referral services. Retail purchase agreements are made with the external vendor, which handles billing, shipping and returns. MGT’s own portal terms and company details are still being finalized.',href:'/',cta:'Explore the applications'},
 shipping:{title:'Delivery details, made clear.',intro:'Shipping and return policies will be published before the store opens.',heading:'No live orders in this preview.',body:'Delivery regions, shipping charges, return windows and refund terms are still to be confirmed. Sample pricing is not a live offer.',href:'/shop',cta:'Return to the shop'},
 partners:{title:'A connected skincare community.',intro:'Partner and merchant onboarding is being prepared for launch.',heading:'Verified relationships only.',body:'No affiliations are currently published. Partner credentials, agreements and payment details will be verified before listings or payouts are enabled.',href:'/company',cta:'About MGT Skin Care'},
 account:{title:'Your personal space.',intro:'Your account will connect your profile, routines and orders.',heading:'Sign-in is not enabled yet.',body:'The identity service must be connected and verified before you can create an account. You can explore the application hub in the meantime.',href:'/',cta:'Explore the applications'},
 orders:{title:'Your orders, together.',intro:'Track purchases and delivery updates from your account.',heading:'Order tracking is not live yet.',body:'Payments and account services are still being connected. This preview does not contain live orders.',href:'/shop',cta:'Return to the shop'},
 membership:{title:'More support for your routine.',intro:'Membership tools are being prepared as part of the portal build.',heading:'Premium is not open for enrollment.',body:'Benefits, pricing and subscription terms will be confirmed before enrollment. No recurring payments are enabled in this preview.',href:'/',cta:'Explore the applications'},
 replenishment:{title:'Ready for your next ritual.',intro:'A place to plan when you need to restock your essentials.',heading:'Reminders are being connected.',body:'Replenishment will let you review reminders and decide when to purchase. Scheduling and notifications are not enabled in this preview.',href:'/routine',cta:'View my routine'}
};
export function generateStaticParams(){return Object.keys(pages).filter(section=>!['shipping','partners','orders','account','learn','support','replenishment'].includes(section)).map(section=>({section}));}
export async function generateMetadata({params}:{params:Promise<{section:string}>}){const {section}=await params;return {title:pages[section]?.title??'Page not found'};}
export default async function SectionPage({params}:{params:Promise<{section:string}>}){const {section}=await params;const page=pages[section];if(!page)notFound();return <div className="page"><article className="content"><span className="eyebrow">MGT SKIN CARE · {section.replace(/-/g,' ').toUpperCase()}</span><h1 className="app-page-title">{page.title}</h1><p className="lead">{page.intro}</p><section className="panel"><h2 style={{fontSize:'1.6rem'}}>{page.heading}</h2><p>{page.body}</p><Link className="button" href={page.href}>{page.cta} <span aria-hidden="true">↗</span></Link></section></article></div>;}

