'use client';
import React,{useState,useRef} from 'react';
import Link from 'next/link';
import {STYLE_SECTIONS} from '@mgt/domain';
const apps=[
 {title:'Skin Match',category:'Discover',description:'Start with your skin. Find a routine shaped around your preferences.',href:'/skin-match',icon:'match',cta:'Find my match',tag:'Start here'},
 {title:'My Routine',category:'My daily care',description:'Your morning and evening steps, organized in one calm place.',href:'/routine',icon:'routine',cta:'Open my routine',tag:'AM / PM'},
 {title:'Skin Coach',category:'My daily care',description:'Explore ingredient guidance and review proposed routine changes.',href:'/coach',icon:'coach',cta:'Open Skin Coach',tag:'Guidance'},
 {title:'The Edit',category:'Discover',description:'Explore specialist stores for skincare, makeup, hair, clothing and headwear.',href:'/shop',icon:'shop',cta:'Find a retailer',tag:'Shop'},
 {title:'My Skin',category:'My daily care',description:'Keep your skin preferences and your current profile in view.',href:'/my-skin',icon:'skin',cta:'View my profile',tag:'Personal'},
 {title:'Replenishment',category:'My daily care',description:'A place for restock reminders, with every purchase in your control.',href:'/replenishment',icon:'refill',cta:'View replenishment',tag:'Plan ahead'}
];
function Icon({kind}:{kind:string}){return <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind==='match'?<><path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z"/><path d="M12 8v8M8 12h8"/></>:kind==='routine'?<><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></>:kind==='coach'?<><path d="M20 11a8 8 0 0 1-8 8H5l-3 3V11a9 9 0 0 1 18 0Z"/><path d="M7 10h8m-8 4h5"/></>:kind==='shop'?<><rect x="4" y="7" width="16" height="14" rx="3"/><path d="M8 7V6a4 4 0 0 1 8 0v1"/></>:kind==='skin'?<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>:<><path d="M20 7a9 9 0 0 0-15-2L2 8m0-5v5h5m-3 9a9 9 0 0 0 15 2l3-3m0 5v-5h-5"/></>}</svg>;}
apps.push(...STYLE_SECTIONS.map(s=>({title:s.title,category:'Beauty & style',description:s.intro,href:'/studio/'+s.id,icon:s.id==='haircare'?'routine':s.id==='clothing'?'shop':'match',cta:'Open my studio',tag:s.id==='personal-color'?'Start your palette':'Connected style'})));
const categories=['All applications','My daily care','Discover','Beauty & style'];
export function AppHub(){
 const [selected,setSelected]=useState(0);const buttons=useRef<(HTMLButtonElement|null)[]>([]);
 const shown=selected===0?apps:apps.filter(a=>a.category===categories[selected]);
 function key(e:React.KeyboardEvent,index:number){let next=index;if(e.key==='ArrowRight')next=(index+1)%categories.length;else if(e.key==='ArrowLeft')next=(index+categories.length-1)%categories.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=categories.length-1;else return;e.preventDefault();setSelected(next);buttons.current[next]?.focus();}
 return <section id="applications" className="hub-apps" aria-labelledby="apps-heading"><div className="section-heading"><div><span className="eyebrow">YOUR APPLICATION HUB</span><h2 id="apps-heading">Everything, in your rhythm.</h2></div><a className="text-link" href="#our-approach">Our approach <span aria-hidden="true">↓</span></a></div><div className="hub-toolbar"><div className="hub-tabs" role="tablist" aria-label="Application categories">{categories.map((c,i)=><button type="button" role="tab" key={c} id={'hub-tab-'+i} aria-controls="hub-panel" aria-selected={selected===i} tabIndex={selected===i?0:-1} ref={el=>{buttons.current[i]=el;}} onClick={()=>setSelected(i)} onKeyDown={e=>key(e,i)}>{c}</button>)}</div><span className="result-count" aria-live="polite">{shown.length} applications</span></div><div role="tabpanel" id="hub-panel" aria-labelledby={'hub-tab-'+selected} tabIndex={0}><div className="app-grid" key={selected}>{shown.map((a,i)=><Link className={'app-card app-'+a.icon} href={a.href} key={a.title} style={{'--card-delay':(i*45)+'ms'} as React.CSSProperties}><div className="row"><span className="app-icon"><Icon kind={a.icon}/></span><span className="app-tag">{a.tag}</span></div><h3>{a.title}</h3><p>{a.description}</p><span className="card-link">{a.cta}<span className="card-arrow" aria-hidden="true">↗</span></span></Link>)}</div></div></section>;
}
