'use client';
import React,{useEffect,useState} from 'react';
import Link from 'next/link';
import {DEFAULT_STYLE,STYLE_OPTIONS,STYLE_SECTIONS,STYLE_PALETTES,stylePlan,normalizeStyle,type StyleProfile,type StyleSection,type StyleOptionKey} from '@mgt/domain';
import {hub,useHub} from '../lib/hub';
import {LoadState} from './HubFrames';
const labels:Record<StyleOptionKey,string>={palette:'Color direction',contrast:'Color contrast',occasion:'Dress for',expression:'Style expression',texture:'Hair texture (optional)',effort:'Time for styling',hairGoal:'Hair color goal',hairPresentation:'How you wear your hair',makeup:'Makeup preference',clothing:'Preferred garments',coverage:'Coverage preference',headwear:'Headwear preference',climate:'Weather to dress for',fastening:'Fastenings',comfort:'Fit & movement',sensory:'Textures & accessories'};
const groups:{title:string;keys:StyleOptionKey[]}[]=[{title:'Color & expression',keys:['palette','contrast','occasion','expression','makeup']},{title:'Hair, your way',keys:['hairPresentation','texture','effort','hairGoal']},{title:'Clothing & personal traditions',keys:['clothing','coverage','headwear','climate']},{title:'Comfort & dressing ease',keys:['fastening','comfort','sensory']}];
export function BeautyStudio({section='personal-color'}:{section?:StyleSection}){
 const state=useHub('/style-profile');
 const [input,setInput]=useState<StyleProfile>(DEFAULT_STYLE),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{if(state.data){setInput(normalizeStyle(state.data.profile?.input));setConsent(!!state.data.profile);}},[state.data]);
 const plan=stylePlan(input),meta=STYLE_SECTIONS.find(s=>s.id===section)!;
 const dirty=JSON.stringify(input)!==JSON.stringify(state.data?.profile?.input);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');setError('');try{await hub('/style-profile',{...input,consent});setMessage('Your shared profile is saved across all six sections.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function download(){const content=['MGT · My beauty & style plan',plan.reason,'Creative suggestions from selected preferences. No photo or live AI analysis.','',...STYLE_SECTIONS.flatMap(s=>[s.title,...plan.cards[s.id].map(c=>c.title+': '+c.text),''])].join('\n');const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='mgt-beauty-style-plan.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function preferences(){return <fieldset disabled={busy} className="studio-inclusive-fields"><legend className="sr-only">Beauty and style preferences</legend><p className="muted">For every gender, background and body. Choose only what helps you; optional attributes can stay unspecified. We do not infer identity or traditions from appearance.</p>{groups.map((group,i)=><details key={group.title} open={i===0?true:undefined}><summary>{group.title}</summary><div className="studio-field-group">{group.keys.map(key=><label className="field" key={key}>{labels[key]}<select value={input[key]} onChange={e=>{setInput({...input,[key]:e.target.value});setMessage('');}}>{STYLE_OPTIONS[key].map(v=><option key={v} value={v}>{v.charAt(0).toUpperCase()+v.slice(1)}</option>)}</select></label>)}</div></details>)}<details><summary>Your own styling brief</summary><label className="field">Garments, traditions or details to keep<textarea rows={5} maxLength={500} value={input.personalNotes} placeholder="Describe what matters to your look, in your own words." onChange={e=>{setInput({...input,personalNotes:e.target.value});setMessage('');}} aria-describedby="style-notes-help"/></label><small id="style-notes-help">Optional · {input.personalNotes.length}/500. Saved with your profile and included verbatim in your download. These notes are a brief for you or your stylist; they are not automatically interpreted.</small></details><label className="studio-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/>Save these preferences for use across my beauty and style sections.</label></fieldset>;}
 return <div className="page beauty-studio"><header className="studio-intro"><div><Link className="text-link" href="/#applications">← Your applications</Link><p className="eyebrow">BEAUTY & STYLE · ONE CONNECTED PROFILE</p><h1>{meta.title}</h1><p className="lead">{meta.intro}</p><p className="muted">Your colors. Your texture. Your expression. Creative suggestions based on the preferences you choose.</p></div><div className="studio-color-mark" aria-label="Current palette">{plan.colors.map(c=><span key={c.name} style={{backgroundColor:c.hex}} title={c.name}/>)}</div></header>
 <nav className="studio-nav" aria-label="Beauty and style sections">{STYLE_SECTIONS.map(s=><Link key={s.id} href={'/studio/'+s.id} aria-current={s.id===section?'page':undefined}>{s.title}</Link>)}</nav>
 <p><Link className="text-link" href={'/shop?segment='+section}>Explore retailers for {meta.title} →</Link></p>
 <LoadState loading={state.loading} error={state.error} retry={state.reload}/>
 {message&&<p role="status" className="notice success">{message}</p>}{error&&<p role="alert" className="notice error">{error}</p>}
 {!state.loading&&!state.error&&<div className="studio-layout"><aside><form className="panel studio-profile" onSubmit={save}><span className="eyebrow">01 · YOUR SHARED PROFILE</span><h2>Make it yours.</h2><p>{state.data?.profile?'Adjust your preferences to preview a new direction.':'Start with this sample palette, then choose the preferences that feel like you.'}</p>{preferences()}<button className="button primary" disabled={busy||!consent||!dirty}>{busy?'Saving…':'Save shared profile'}</button><small>{dirty?'Preview only · save before opening another section.':'Saved · all sections use these preferences.'} Guest preferences stay with this browser session; sign in to retain them with your account.</small><Link className="text-link" href="/account">My account →</Link></form></aside>
 <div className="studio-results"><section className="panel"><div className="row"><span className="eyebrow">02 · YOUR COLOR STORY</span><span className="pill">{input.palette} · {input.contrast}</span></div><h2>A thread through every look.</h2><div className="studio-swatches">{plan.colors.map(c=><div key={c.name}><span style={{backgroundColor:c.hex}}/><strong>{c.name}</strong><small>{c.hex}</small></div>)}</div><p className="muted">{plan.reason}</p>{section==='personal-color'&&<div className="studio-comparisons" aria-label="Compare color directions">{Object.entries(STYLE_PALETTES).map(([key,colors])=><button type="button" className="studio-palette-choice" key={key} aria-pressed={input.palette===key} onClick={()=>{setInput({...input,palette:key as StyleProfile['palette']});setMessage('');}}><span>{colors.map(c=><i key={c.name} style={{backgroundColor:c.hex}}/>)}</span>{key} {input.palette===key?'✓':''}</button>)}</div>}</section>
 <section aria-labelledby="studio-plan-heading"><span className="eyebrow">03 · YOUR {section==='style'?'COMPLETE LOOK':'DIRECTION'}</span><h2 id="studio-plan-heading">{section==='personal-color'?'Find your common thread.':meta.title+' · your plan'}</h2><div className="studio-plan-grid">{plan.cards[section].map((c,i)=><article className="panel" key={c.title}><span className="studio-step">0{i+1}</span><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></section>
 <section className="panel studio-next"><div><h2>Take the whole look with you.</h2><p>Download all six sections using your current selections to keep or share with your stylist.</p><small>Preference-based inspiration. No photo analysis, live AI assessment, or product shade verification.</small></div><button type="button" className="button" onClick={download}>Download complete plan</button></section><div className="studio-related"><Link className="text-link" href="/skin-match">Connect your skincare routine →</Link>{section!=='style'&&<Link className="text-link" href="/studio/style">View the complete look →</Link>}</div></div></div>}
 </div>;
}
