'use client';
import React,{useState} from 'react';import {hub,useHub} from '../lib/hub';import {LoadState} from './HubFrames';
function Readiness(){const state=useHub('/admin/readiness');return <><section className="panel"><h2>Launch setup</h2><LoadState {...state} retry={state.reload}/>{state.data&&<><p>{state.data.note}</p><dl className="profile-details">{state.data.checks.map((c:any)=><div key={c.name}><dt>{c.name}</dt><dd>{c.configured?'Configured':'Needs setup'}</dd></div>)}</dl><button className="button" onClick={state.reload}>Refresh checks</button></>}</section><CatalogHealth/></>;}
function CatalogHealth(){const state=useHub('/admin/catalog-health');return <section className="panel"><div className="section-heading"><div><span className="eyebrow">DATA QUALITY</span><h2>Catalog readiness</h2></div></div><LoadState {...state} retry={state.reload}/>{state.data&&<><p>{state.data.note}</p>{state.data.ready?<p className="notice success">Catalog metadata meets the current readiness checks.</p>:<ul className="notice error">{state.data.warnings.map((warning:string)=><li key={warning}>{warning}</li>)}</ul>}<div className="skin-overview">{[['Products',state.data.products.total],['Active',state.data.products.active],['Approved',state.data.products.approved],['Sample',state.data.products.sample],['Approved rules',state.data.rules.approved]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="table-wrap"><table><thead><tr><th>Required slot</th><th>Active</th><th>Approved</th><th>Sample</th></tr></thead><tbody>{state.data.slot_coverage.map((row:any)=><tr key={row.slot}><td>{row.slot.replace(/_/g,' ')}</td><td>{row.active}</td><td>{row.approved}</td><td>{row.sample}</td></tr>)}</tbody></table></div>{state.data.rules.unreviewed_ingredients.length>0&&<p className="muted">Unreviewed ingredient keys: {state.data.rules.unreviewed_ingredients.join(', ')}</p>}<button className="button" onClick={state.reload}>Refresh catalog health</button></>}</section>;}
function AiRouting(){const state=useHub('/admin/ai-routing');return <section className="panel"><div className="section-heading"><div><span className="eyebrow">QUALITY OPERATIONS</span><h2>Analysis routing · last 24 hours</h2></div></div><LoadState {...state} retry={state.reload}/>{state.data&&<>{state.data.requests===0?<p className="muted">No analysis calls have been recorded in this window.</p>:<><p className="muted">{state.data.requests} telemetry records · ${(Number(state.data.cost_cents)/100).toFixed(4)} estimated usage cost</p><div className="table-wrap"><table><thead><tr><th>Configuration</th><th>Records</th><th>Fallbacks</th><th>Validation</th><th>P95</th></tr></thead><tbody>{state.data.routes.map((route:any)=><tr key={route.route}><td>{route.route}</td><td>{route.requests}</td><td>{route.fallbacks}</td><td>{route.validation_failures?'Review needed':'Clear'}</td><td>{route.p95_latency_ms} ms</td></tr>)}</tbody></table></div></>}<button className="button" onClick={state.reload}>Refresh routing</button></>}</section>;}
function AiEconomics(){const state=useHub('/admin/ai-economics');const pct=(value:number)=>`${(Number(value)*100).toFixed(1)}%`;return <section className="panel"><div className="section-heading"><div><span className="eyebrow">ANALYSIS ECONOMICS</span><h2>Spend, quality and exposure</h2></div></div><LoadState {...state} retry={state.reload}/>{state.data&&<>{state.data.alerts?.length?<ul className="notice error">{state.data.alerts.map((alert:string)=><li key={alert}>{alert}</li>)}</ul>:<p className="notice success">No analysis cost or validation alerts in this window.</p>}<div className="skin-overview">{[['Requests',state.data.totals.requests],['Success rate',pct(state.data.totals.success_rate)],['Fallback rate',pct(state.data.totals.fallback_rate)],['Usage cost','$'+(Number(state.data.totals.cost_cents)/100).toFixed(4)],['Pending holds',state.data.pending_reservations],['Stale holds',state.data.stale_reservations]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{state.data.by_route?.length>0&&<div className="table-wrap"><table><thead><tr><th>Configuration</th><th>Requests</th><th>Cost</th><th>Failures</th><th>Validation</th></tr></thead><tbody>{state.data.by_route.map((row:any)=><tr key={row.route}><td>{row.route}</td><td>{row.requests}</td><td>${(Number(row.cost_cents)/100).toFixed(4)}</td><td>{row.failures}</td><td>{row.validation_failures}</td></tr>)}</tbody></table></div>}<button className="button" onClick={state.reload}>Refresh economics</button></>}</section>;}
function PrivacyOperations(){const state=useHub('/admin/deletions');const label=(value:string)=>value.replace(/_/g,' ');return <section className="panel"><div className="section-heading"><div><span className="eyebrow">PRIVACY OPERATIONS</span><h2>Account deletion queue</h2></div></div><LoadState {...state} retry={state.reload}/>{state.data&&<><p>{state.data.privacy_note}</p>{!state.data.identity_deletion_configured&&<p className="notice error">Account identity deletion is not configured. Due requests will pause before portal data is erased.</p>}<div className="skin-overview">{[['Queued',state.data.summary.total],['Due',state.data.summary.due],['Blocked',state.data.summary.blocked],['Processing',state.data.summary.processing],['Completed · 30 days',state.data.summary.completed_30_days]].map(([name,value])=><div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div>{state.data.queue.length?<div className="table-wrap"><table><thead><tr><th>Request</th><th>Scheduled</th><th>Status</th><th>Blockers</th></tr></thead><tbody>{state.data.queue.map((item:any)=><tr key={item.request_id||item.not_before}><td>{item.request_id?item.request_id.slice(0,8):'Legacy request'}</td><td>{item.not_before?new Date(item.not_before).toLocaleString():'Invalid date'}</td><td>{item.status}{item.due?' · due':''}</td><td>{[...(item.blocked_reasons||[]).map(label),...(item.service_error?['identity service error']:[])].join(', ')||'None'}</td></tr>)}</tbody></table></div>:<p className="notice success">No account deletion requests are waiting.</p>}{state.data.recent_completions.length>0&&<p className="muted">{state.data.recent_completions.length} anonymous completion proof{state.data.recent_completions.length===1?'':'s'} recorded in the last 30 days.</p>}<button className="button" onClick={state.reload}>Refresh privacy operations</button></>}</section>;}
function SubscriptionWebhooks(){const state=useHub('/admin/subscription-webhooks');const label=(value:string)=>value.replace(/_/g,' ');return <section className="panel"><div className="section-heading"><div><span className="eyebrow">BILLING OPERATIONS</span><h2>Subscription webhook reconciliation</h2></div></div><LoadState {...state} retry={state.reload}/>{state.data&&<><p>{state.data.privacy_note}</p>{!state.data.configured&&<p className="notice error">Subscription webhook processing is not fully configured.</p>}{state.data.alerts?.length?<ul className="notice error">{state.data.alerts.map((alert:string)=><li key={alert}>{alert}</li>)}</ul>:<p className="notice success">No failed or stalled signed subscription events in the last 24 hours.</p>}<div className="skin-overview">{[['Events',state.data.summary.events],['Deliveries',state.data.summary.delivery_attempts],['Processed',state.data.summary.processed],['Duplicates',state.data.summary.duplicates],['Failed',state.data.summary.failed],['Stalled',state.data.summary.stalled]].map(([name,value])=><div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div>{state.data.receipts.length>0&&<div className="table-wrap"><table><thead><tr><th>Event</th><th>Type</th><th>Outcome</th><th>Last delivery</th></tr></thead><tbody>{state.data.receipts.map((item:any)=><tr key={item.event_id}><td>{item.event_id}</td><td>{label(item.type)}</td><td>{item.stalled?'stalled':label(item.status)}{item.error_code?' · '+label(item.error_code):''}</td><td>{item.last_received_at?new Date(item.last_received_at).toLocaleString():'Unknown'}</td></tr>)}</tbody></table></div>}<button className="button" onClick={state.reload}>Refresh webhook activity</button></>}</section>;}
function SupportMetrics(){const state=useHub('/admin/support-metrics');const label=(value:string)=>value.replace(/_/g,' ');return <section className="panel"><div className="section-heading"><div><span className="eyebrow">SUPPORT OPERATIONS</span><h2>Guidance and request flow · last 30 days</h2></div></div><LoadState {...state} retry={state.reload}/>{state.data&&<><p>{state.data.interpretation}</p><p className="muted">{state.data.privacy_note}</p><div className="skin-overview">{[['Guidance',state.data.events.guidance_requested||0],['Handoffs offered',state.data.handoff_funnel.offered],['Support opened',state.data.handoff_funnel.support_opened],['Handoffs saved',state.data.handoff_funnel.request_saved],['Escalations',state.data.events.escalation_marked||0],['Resolved',state.data.statuses.closed]].map(([name,value])=><div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div>{state.data.guidance_by_role.length>0&&<div className="table-wrap"><table><thead><tr><th>Guidance topic</th><th>Requests</th></tr></thead><tbody>{state.data.guidance_by_role.map((row:any)=><tr key={row.role}><td>{label(row.role)}</td><td>{row.requests}</td></tr>)}</tbody></table></div>}{state.data.escalation_reasons.length>0&&<div className="table-wrap"><table><thead><tr><th>Escalation reason</th><th>Marked</th></tr></thead><tbody>{state.data.escalation_reasons.map((row:any)=><tr key={row.reason}><td>{label(row.reason)}</td><td>{row.count}</td></tr>)}</tbody></table></div>}<button className="button" onClick={state.reload}>Refresh support flow</button></>}</section>;}
function ReferralMetrics(){const state=useHub('/admin/referral-metrics');return <section className="panel"><div className="section-heading"><div><span className="eyebrow">REFERRAL DISCOVERY</span><h2>Retailer engagement · last 30 days</h2></div></div><LoadState {...state} retry={state.reload}/>{state.data&&<><p>{state.data.interpretation}</p><p className="muted">{state.data.privacy_note}</p><div className="skin-overview">{[['Outbound opens',state.data.summary.outbound],['Saved',state.data.summary.saved],['Unsaved',state.data.summary.unsaved]].map(([name,value])=><div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div>{state.data.by_retailer.length?<div className="table-wrap"><table><thead><tr><th>Retailer</th><th>Outbound</th><th>Saved</th><th>Unsaved</th></tr></thead><tbody>{state.data.by_retailer.map((row:any)=><tr key={row.retailer_id}><td>{row.name}</td><td>{row.outbound}</td><td>{row.saved}</td><td>{row.unsaved}</td></tr>)}</tbody></table></div>:<p className="muted">No retailer engagement has been recorded in this window.</p>}<p className="notice">Commercial agreements: {state.data.commercial_agreements}. Do not interpret these actions as retailer orders or revenue.</p><button className="button" onClick={state.reload}>Refresh referral engagement</button></>}</section>;}
export function ConnectedAdmin({kind}:{kind:'knowledge'|'rule'|'operations'}){
 const state=useHub('/admin'),session=useHub('/session'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function save(path:string,body:unknown){setBusy(true);setError('');setMessage('');try{await hub(path,body);state.reload();setMessage('Saved.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const data=state.data,roles:string[]=data?.roles||[];const canDraft=kind==='knowledge'?roles.some(r=>['superadmin','sme','catalog_editor'].includes(r)):roles.some(r=>['superadmin','sme'].includes(r));
 const label=(value:string)=>value.replace(/_/g,' ');
 const supportOperator=roles.some(r=>['superadmin','compliance'].includes(r));
 return <>
  <h1 className="app-page-title">{kind==='operations'?'Portal operations':kind==='knowledge'?'Knowledge review':'Ingredient rules'}</h1>
  <p>Access uses your signed-in account and assigned roles.</p>
  <LoadState {...state} retry={state.reload}/>
  {error&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status" className="notice success">{message}</p>}
  {data&&<>{kind==='operations'?<>
   {supportOperator&&<><Readiness/><SupportMetrics/><ReferralMetrics/><PrivacyOperations/><SubscriptionWebhooks/><AiEconomics/><AiRouting/></>}
   <div className="skin-overview">{[['Products',data.products.length],['Articles',data.knowledge.length],['Support requests',data.tickets.length]].map(([name,count])=><div key={name}><span>{name}</span><strong>{count}</strong></div>)}</div>
   <h2>Support requests</h2>
   {data.tickets.map((t:any)=><article className="panel support-ticket" key={t.id}>
    <div className="row"><h3>{t.subject}</h3><span className="pill">{label(t.status||'open')}</span></div>
    <p className="muted">{label(t.request_type||'portal_help')} · {t.assigned_to?(t.assigned_to===session.data?.account?.id?'Assigned to you':'Assigned to another operator'):'Unassigned'}{t.escalation_reason?' · '+label(t.escalation_reason):''}</p>
    <p className="muted support-reference">Reference: {t.id}{t.created_at?' · Saved '+new Date(t.created_at).toLocaleString():''}{t.updated_at&&t.updated_at!==t.created_at?' · Updated '+new Date(t.updated_at).toLocaleString():''}</p>
    <p className="support-message">{t.message}</p>
    {t.replies.map((reply:any,index:number)=><blockquote key={index}><p>{reply.text}</p>{reply.at&&<small>{new Date(reply.at).toLocaleString()}</small>}</blockquote>)}
    {supportOperator&&<form key={t.id+':'+t.status+':'+t.updated_at} className="stack" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void save('/admin/ticket',{id:t.id,reply:form.get('reply'),status:form.get('status'),escalation_reason:form.get('escalation_reason')});}}>
     <label className="field">Request status<select name="status" defaultValue={t.status||'open'}><option value="open">Open</option><option value="in_review">In review</option><option value="waiting_customer">Waiting for customer</option><option value="closed">Resolved</option></select></label>
     <label className="field">Escalation reason<select name="escalation_reason" defaultValue={t.escalation_reason||'none'}><option value="none">No escalation</option><option value="content_safety">Content safety</option><option value="account_privacy">Account or privacy</option><option value="billing_scope">Billing scope</option><option value="retailer_purchase">Retailer purchase</option><option value="technical_issue">Technical issue</option><option value="specialist_review">Specialist review</option><option value="other">Other</option></select></label>
     <label className="field">Customer reply<textarea name="reply" maxLength={4000} placeholder="Required when waiting for the customer, resolving, or reopening."/></label>
     <button className="button" disabled={busy}>Update request</button>
    </form>}
   </article>)}
   <h2>Recent audit activity</h2><div className="table-wrap"><table><thead><tr><th>Action</th><th>Time</th></tr></thead><tbody>{data.audit.slice(-20).reverse().map((a:any)=><tr key={a.id}><td>{a.action}</td><td>{a.at}</td></tr>)}</tbody></table></div>
  </>:<>
   {canDraft&&<form className="panel stack" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);const body=Object.fromEntries(form);void save('/admin/'+kind,kind==='rule'?{...body,sensitivity_ceiling_required:Number(form.get('sensitivity_ceiling_required'))}:body);}}><h2>Create a draft</h2>{(kind==='knowledge'?['title','source_url','body']:['ingredient_key','display_name','sensitivity_ceiling_required','rationale']).map(field=><label className="field" key={field}>{label(field)}{['body','rationale'].includes(field)?<textarea required name={field} maxLength={field==='body'?4000:1000}/>:<input required name={field} type={field==='source_url'?'url':field==='sensitivity_ceiling_required'?'number':'text'} step={field==='sensitivity_ceiling_required'?'.01':undefined} min={field==='sensitivity_ceiling_required'?0:undefined} max={field==='sensitivity_ceiling_required'?1:undefined}/>}</label>)}<button className="button primary" disabled={busy}>Save draft</button></form>}
   {(kind==='knowledge'?data.knowledge:data.rules).map((item:any)=><article className="panel" key={item.id||item.ingredient_key}><div className="row"><h3>{item.title||item.display_name}</h3><span className="pill">{item.status}</span></div><p style={{whiteSpace:'pre-wrap'}}>{item.body||item.rationale}</p>{item.status!=='approved'&&!item.sample&&roles.includes('sme')&&item.author_id!==session.data?.account?.id&&<button className="button" disabled={busy} onClick={()=>void save('/admin/'+kind+'/approve',kind==='knowledge'?{id:item.id}:{ingredient_key:item.ingredient_key})}>Approve reviewed draft</button>}</article>)}
  </>}</>}
 </>;
}
