'use client';
import React from 'react';
import {shareShopUrl} from '../lib/shop-state';
export type ComparisonRetailer={id:string;name:string;url:string;region:string;specialty:string;description:string;segments:string[];type:string;checked_at:string;source_url:string};
export function RetailerComparison({retailers,segments,remove,clear}:{retailers:ComparisonRetailer[];segments:{id:string;label:string}[];remove:(id:string)=>void;clear:()=>void}){
 const [message,setMessage]=React.useState('');
 const selectionKey=retailers.map(r=>r.id).join(',');
 React.useEffect(()=>setMessage(''),[selectionKey]);
 function comparisonLink(){return shareShopUrl(window.location.href,retailers.map(r=>r.id));}
 function download(){const content=['MGT · Retailer shortlist','Independent directory listings. Confirm current prices, fit, shades, delivery and returns with each store.','',...retailers.flatMap(r=>[r.name,r.specialty,r.description,'Storefront: '+r.region,'Segments: '+r.segments.map(id=>segments.find(s=>s.id===id)?.label||id).join(', '),'Store type: '+r.type,'Website: '+r.url,'Listing checked: '+r.checked_at,'']),'Restore comparison: '+comparisonLink()].join('\n');const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='mgt-retailer-shortlist.txt';a.click();setMessage('Shortlist downloaded.');setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function copy(){try{await navigator.clipboard.writeText(comparisonLink());setMessage('Comparison link copied.');}catch{setMessage('Copy the page address from your browser to keep this comparison.');}}
 return <section className="shop-comparison panel" aria-labelledby="comparison-heading"><div className="row"><div><span className="eyebrow">YOUR RETAILER SHORTLIST</span><h2 id="comparison-heading">Compare your destinations.</h2></div><span className="pill">{retailers.length} / 3 selected</span></div><p>Select Compare on up to three stores. Your selections stay in this page’s address, even when you change filters.</p>{!retailers.length?<p className="muted">No stores selected yet. Browse below to start your comparison.</p>:<><div className="table-wrap" role="region" aria-label="Retailer comparison table" tabIndex={0}><table><caption className="sr-only">Compare selected retailers by specialty, storefront region and listed segments</caption><thead><tr><th scope="col">Compare</th>{retailers.map(r=><th scope="col" key={r.id}>{r.name}<button className="text-button" type="button" aria-label={'Remove '+r.name+' from comparison'} onClick={()=>remove(r.id)}>Remove</button></th>)}</tr></thead><tbody>{[{label:'Specialty',value:(r:ComparisonRetailer)=>r.specialty},{label:'Storefront region',value:(r:ComparisonRetailer)=>r.region},{label:'Segments',value:(r:ComparisonRetailer)=>r.segments.map(id=>segments.find(s=>s.id===id)?.label||id).join(', ')},{label:'Store type',value:(r:ComparisonRetailer)=>r.type},{label:'Listing checked',value:(r:ComparisonRetailer)=>r.checked_at}].map(row=><tr key={row.label}><th scope="row">{row.label}</th>{retailers.map(r=><td key={r.id}>{row.value(r)}</td>)}</tr>)}<tr><th scope="row">Explore</th>{retailers.map(r=><td key={r.id}><a href={r.url} className="text-link" target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">Visit {r.name} ↗<span className="sr-only">, opens a new tab</span></a></td>)}</tr></tbody></table></div><p className="muted">Prices, availability, delivery coverage and personal suitability are not compared. Check those with each retailer.</p><div className="actions"><button className="button" type="button" onClick={download}>Download shortlist</button><button className="button" type="button" onClick={copy}>Copy comparison link</button><button className="text-button" type="button" onClick={clear}>Clear comparison</button></div></>}{message&&<p role="status">{message}</p>}</section>;
}
