'use client';
import React,{useEffect,useState} from 'react';
import Link from 'next/link';
import {RetailerComparison} from './RetailerComparison';
import {readShopState,updateShopUrl,shareShopUrl} from '../lib/shop-state';
import {hub,useHub} from '../lib/hub';
import {AppFrame,LoadState} from './HubFrames';
type Segment={id:string;label:string;studio:string};
type Retailer={id:string;name:string;url:string;region:string;specialty:string;description:string;segments:string[];type:string;checked_at:string;source_url:string};
export function RetailerDirectory({savedOnly=false}:{savedOnly?:boolean}){
 const [compare,setCompare]=useState<string[]>([]);
 const state=useHub('/retailers'),saved=useHub('/saved-retailers');
 const [query,setQuery]=useState(''),[region,setRegion]=useState('All'),[specialty,setSpecialty]=useState('All'),[segment,setSegment]=useState('all'),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const ids:string[]=saved.data?.ids||[],listings:Retailer[]=state.data?.retailers||[],segments:Segment[]=state.data?.segments||[];
 useEffect(()=>{if(!state.data)return;const sync=()=>{const next=readShopState(window.location.search,state.data.retailers,state.data.segments);setCompare(next.compare);setSegment(next.segment);setQuery(next.query);setRegion(next.region);setSpecialty(next.specialty);setShareMessage('');};sync();window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[state.data]);
 const [shareMessage,setShareMessage]=useState('');
 function writeFilters(values:Record<string,string>){window.history.replaceState(null,'',updateShopUrl(window.location.href,values));setShareMessage('');}
 function choose(value:string){setSegment(value);setSpecialty('All');writeFilters({segment:value,specialty:'All'});}
 function updateComparison(next:string[]){setCompare(next);writeFilters({compare:next.join(',')});}
 async function share(){try{await navigator.clipboard.writeText(shareShopUrl(window.location.href,compare));setShareMessage('Shop link copied. It restores your filters and comparison.');}catch{setShareMessage('Copy the page address from your browser to restore this view.');}}
 function toggleComparison(id:string){updateComparison(compare.includes(id)?compare.filter(x=>x!==id):compare.length<3?[...compare,id]:compare);}
 const available=listings.filter(r=>!savedOnly||ids.includes(r.id));
 const visible=available.filter(r=>(segment==='all'||r.segments.includes(segment))&&(region==='All'||r.region===region)&&(specialty==='All'||r.specialty===specialty)&&[r.name,r.description,r.specialty,...r.segments].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
 const selected=segments.find(s=>s.id===segment);
 async function toggle(id:string){setBusy(id);setError('');try{await hub('/saved-retailers',{id,saved:!ids.includes(id)});}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 function clear(){setQuery('');setRegion('All');setSpecialty('All');setSegment('all');writeFilters({q:'',region:'All',specialty:'All',segment:'all'});}
 return <AppFrame title={savedOnly?'Your saved destinations':'The Beauty & Style Edit'}>
 <div className="retailer-intro"><div><span className="eyebrow">YOUR LOOK · YOUR DESTINATIONS</span><p className="lead">{savedOnly?'Keep your favorite beauty, hair and wardrobe stores together.':'From your daily ritual to your complete look.'}</p><p>Explore specialist stores across beauty, hair, clothing and headwear. Start with a segment, find a specialty, and save the destinations you want to revisit.</p><Link className="text-link" href={savedOnly?'/shop':'/saved'}>{savedOnly?'← Explore all retailers':'View saved retailers →'}</Link></div><img src="/images/skincare-still-life.png" width="1536" height="1024" alt="Illustrative skincare still life in violet and amber"/></div>
 <div className="notice"><strong>Shop directly with each retailer.</strong> Payments, shipping and returns happen on its site. This starter directory is independently selected; listings are not personal fit, shade or suitability guarantees.</div>
 <LoadState {...state} retry={state.reload}/>{saved.error&&<div className="notice error" role="alert">Saved retailers could not load. <button className="text-button" onClick={saved.reload}>Try again</button></div>}{error&&<p role="alert" className="notice error">{error}</p>}
 {!state.loading&&!state.error&&<><section aria-label="Shop by segment" className="shop-segments"><button type="button" aria-pressed={segment==='all'} onClick={()=>choose('all')}><strong>All destinations</strong><span>{available.length} stores to explore</span></button>{segments.map(s=><button type="button" key={s.id} aria-pressed={segment===s.id} onClick={()=>choose(s.id)}><strong>{s.label}</strong><span>{available.filter(r=>r.segments.includes(s.id)).length} destinations</span></button>)}</section>
 <section className="shop-context"><div><span className="eyebrow">{selected?'EXPLORE YOUR SEGMENT':'ONE CONNECTED WORKSPACE'}</span><h2>{selected?.label||'Start with your style.'}</h2><p>{segment==='personal-color'?'Explore makeup and accessories by color. These listings are not verified personal shade matches.':'Your studio helps plan a look. The shop helps you explore where to find it.'}</p></div><Link className="button" href={selected?.studio||'/studio/personal-color'}>{selected?'Open this styling tool':'Build my color profile'} →</Link></section>
 <RetailerComparison retailers={compare.map(id=>listings.find(r=>r.id===id)).filter((r):r is Retailer=>!!r)} segments={segments} remove={id=>updateComparison(compare.filter(x=>x!==id))} clear={()=>updateComparison([])}/>
 <div className="retailer-controls"><label className="field">Find a retailer<input type="search" value={query} placeholder="Name, specialty or segment" maxLength={160} onChange={e=>{setQuery(e.target.value);writeFilters({q:e.target.value});}}/></label><label className="field">Storefront region<select value={region} onChange={e=>{setRegion(e.target.value);writeFilters({region:e.target.value});}}>{['All',...new Set(listings.map(r=>r.region))].map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Specialty<select value={specialty} onChange={e=>{setSpecialty(e.target.value);writeFilters({specialty:e.target.value});}}>{['All',...new Set(listings.filter(r=>segment==='all'||r.segments.includes(segment)).map(r=>r.specialty))].map(x=><option key={x}>{x}</option>)}</select></label></div>
 <p className="muted">Storefront region does not confirm delivery to your address. Check sizes, shades, stock and delivery with the store.</p>
 {!(savedOnly&&(saved.loading||saved.error))&&<><div className="row"><p className="muted" role="status">{visible.length} matching {visible.length===1?'destination':'destinations'}</p><div className="row"><button className="button" type="button" onClick={share}>Copy shop link</button><button className="text-button" type="button" onClick={clear}>Clear filters</button></div></div>{shareMessage&&<p role="status">{shareMessage}</p>}<div className="retailer-grid">{visible.map(r=><article className="retailer-card" key={r.id}><div className="row"><span className="pill">{r.specialty}</span><span className="muted">{r.region}</span></div><h2>{r.name}</h2><p>{r.description}</p><div className="shop-card-segments">{r.segments.map(id=><span key={id}>{segments.find(s=>s.id===id)?.label}</span>)}</div><p className="retailer-domain">{new URL(r.url).hostname}</p><small>{r.type} · Independent listing</small><div className="retailer-actions"><a className="button primary" href={r.url} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">Visit retailer ↗<span className="sr-only">: {r.name}, opens a new tab</span></a><button type="button" className="button" disabled={!!busy||saved.loading||!!saved.error} aria-pressed={ids.includes(r.id)} aria-label={(ids.includes(r.id)?'Unsave ':'Save ')+r.name} onClick={()=>toggle(r.id)}>{busy===r.id?'Saving…':ids.includes(r.id)?'Saved ✓':'Save'}</button></div><button type="button" className="button shop-compare-toggle" aria-pressed={compare.includes(r.id)} disabled={compare.length>=3&&!compare.includes(r.id)} onClick={()=>toggleComparison(r.id)} aria-label={(compare.includes(r.id)?'Remove ':'Compare ')+r.name}>{compare.includes(r.id)?'Selected for comparison ✓':compare.length>=3?'Comparison full (3 stores)':'Compare this retailer'}</button><small>Checked {r.checked_at} · <a href={r.source_url} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">Listing source<span className="sr-only"> for {r.name}, opens a new tab</span> ↗</a></small></article>)}</div>{!visible.length&&<section className="empty"><h2>{savedOnly&&!ids.length?'No saved retailers yet.':'No destinations match these filters.'}</h2>{savedOnly&&!ids.length?<Link className="button primary" href="/shop">Explore retailers</Link>:<button className="button" onClick={clear}>Show all destinations</button>}</section>}</>}
 </>}
 <section className="panel"><h2 style={{fontSize:'1.5rem'}}>A small selection. Room to grow.</h2><p>These stores are a starting point, not a complete representation of cultures, sizes or styling needs. No referral fees, sponsored placements or MGT commercial partnerships are active in this directory.</p><Link className="text-link" href="/support">Suggest a specialist retailer →</Link></section></AppFrame>;
}
