'use client';
import React,{useEffect,useRef,useState} from 'react';import {useRouter} from 'next/navigation';
import {CORE_STEPS,OPTIONAL_STEPS,toProfileInput,type AnswerState} from '@mgt/shared';
import {SkinMatchStep} from '../../components/SkinMatchStep';import {hub,useHub} from '../../lib/hub';import {AppFrame,LoadState,SampleNotice} from '../../components/HubFrames';
const steps=[...CORE_STEPS,...OPTIONAL_STEPS];
export default function SkinMatchPage(){
 const saved=useHub('/profile'),settings=useHub('/session');const [index,setIndex]=useState(0),[answers,setAnswers]=useState<AnswerState>({}),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const [returnToReview,setReturnToReview]=useState(false);const initialized=useRef(false),previous=useRef(0);const router=useRouter();
 const editingRevision=useRef<string|null>(null);
 useEffect(()=>{if(saved.data&&!initialized.current){if(saved.data.profile)setAnswers(saved.data.profile.input);editingRevision.current=saved.data.revision??null;initialized.current=true;}},[saved.data]);
 useEffect(()=>{if(previous.current!==index){document.getElementById(index<steps.length?'step-prompt':'review-heading')?.focus();previous.current=index;}},[index]);
 async function save(){setBusy(true);setError('');try{await hub('/profile',{...toProfileInput(answers),consent,expected_revision:editingRevision.current});router.push('/skin-match/results');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function describe(step:typeof steps[number]){const raw=answers[step.id];return(Array.isArray(raw)?raw:[raw]).filter(Boolean).map(v=>step.choices.find(c=>c.value===v)?.label||String(v).replace(/_/g,' ')).join(', ')||'None selected';}
 return <AppFrame title={saved.data?.profile?'Update your Skin Match':'Find your Skin Match'}>{settings.data?.demo&&<SampleNotice/>}<LoadState {...saved} retry={saved.reload}/>{!saved.loading&&!saved.error&&<div className="panel"><div className="row match-position"><span>{index<steps.length?'Your preferences':'Review & save'}</span><span>{index+1} of {steps.length+1}</span></div><div role="progressbar" aria-label="Skin Match progress" aria-valuenow={index+1} aria-valuemin={0} aria-valuemax={steps.length+1} className="match-progress"><span style={{width:((index+1)/(steps.length+1)*100)+'%'}}/></div>{index<steps.length?<SkinMatchStep step={steps[index]} stepIndex={index} totalSteps={steps.length+1} answers={answers} onAnswer={(id,v)=>setAnswers(a=>({...a,[id]:v}))} nextLabel={returnToReview?'Back to review':undefined} onNext={()=>{setIndex(returnToReview?steps.length:index+1);setReturnToReview(false);}} onBack={()=>{setIndex(returnToReview?steps.length:Math.max(0,index-1));setReturnToReview(false);}}/>:<section><h2 id="review-heading" tabIndex={-1}>Make sure this feels like you.</h2><p>Review your preferences before saving. You can edit any answer.</p><dl className="review-answers">{steps.map((step,i)=><div key={step.id}><div><dt>{step.prompt}</dt><dd>{describe(step)}</dd></div><button className="text-button" type="button" aria-label={'Edit: '+step.prompt} onClick={()=>{setReturnToReview(true);setIndex(i);}}>Edit</button></div>)}</dl><p>Your preferences are saved to this portal session. Guest access expires after 24 hours. Account sign-in, when available, connects them to your account.</p><label className="check-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I agree to save these skincare preferences for matching.</label><div className="actions"><button className="button" disabled={busy} onClick={()=>setIndex(i=>i-1)}>Back</button><button className="button primary" disabled={!consent||busy} onClick={save}>{busy?'Saving your match…':'Save and see my routine'}</button></div></section>}{error&&<p role="alert" className="notice error">{error}</p>}</div>}</AppFrame>;}

