'use client';
import React,{useState,useRef,useEffect} from 'react';import Link from 'next/link';
import {hub,useHub} from '../../lib/hub';import {AppFrame,LoadState} from '../../components/HubFrames';
export default function Coach(){
 const state=useHub('/session'),[message,setMessage]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[messages,setMessages]=useState<any[]>([]);
 const composer=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!messages.length)return;const answers=composer.current?.parentElement?.querySelectorAll<HTMLElement>('.coach-exchange');const latest=answers?.[answers.length-1];if(latest){latest.tabIndex=-1;latest.focus();}},[messages.length]);
 const ready=state.data?.ai_configured===true&&!!state.data?.account;
 const starters=['What does a moisturizer do?','How does sunscreen fit into a morning routine?','What should I know about niacinamide?'];
 function chooseQuestion(question:string){setMessage(question);setError('');composer.current?.parentElement?.querySelector('textarea')?.focus();}
 async function send(e:React.FormEvent){e.preventDefault();if(busy||!ready||!consent||!message.trim())return;const question=message.trim();setBusy(true);setError('');try{const answer=await hub('/coach',{message:question,ai_consent:consent});setMessages(m=>[...m,{question,answer}]);setMessage('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <AppFrame title="Skin Coach"><p className="lead">A space for your skincare questions.</p><p>Explore cosmetic skincare questions using the reviewed library. This service cannot diagnose symptoms or prescribe treatment.</p>
 <LoadState {...state} retry={state.reload}/>
 {!state.loading&&!state.error&&!state.data?.ai_configured&&<p className="notice">The platform analysis service is not connected yet. Answers will be available after service configuration and knowledge review.</p>}
 {!state.loading&&!state.error&&!state.data?.account&&<p className="notice"><Link className="text-link" href="/account">Sign in to ask Skin Coach →</Link> You can draft your question here first.</p>}
 <div ref={composer} className="coach-starters" role="group" aria-label="Question starters"><span className="eyebrow">START WITH A QUESTION</span>{starters.map(question=><button type="button" className="button" key={question} disabled={busy} onClick={()=>chooseQuestion(question)}>{question}</button>)}</div>
 <div className="coach-links"><Link className="text-link" href="/routine">Review my routine →</Link><Link className="text-link" href="/learn">Explore the reviewed library →</Link></div>
 {busy&&<p className="notice" role="status">Finding and verifying relevant reviewed excerpts…</p>}
 <section className="coach-conversation" aria-label="Conversation">{!messages.length?<div className="coach-welcome"><span className="eyebrow">INGREDIENTS · ROUTINES · DAILY CARE</span><h2>What would you like to understand?</h2><p>Ask one question at a time. You can review any cited sources alongside the answer.</p></div>:messages.map((m,i)=><article className="coach-exchange" key={i}><div className="coach-question"><span className="eyebrow">YOUR QUESTION</span><p>{m.question}</p></div><div className="coach-answer"><span className="eyebrow">SKIN COACH · REVIEWED RESPONSE</span><p>{m.answer.text}</p>{m.answer.citations?.length>0&&<div className="coach-sources"><h3>Sources to explore</h3>{m.answer.citations.map((c:any,j:number)=><blockquote key={c.knowledge_id+'-'+j}><p>{c.text}</p><a className="text-link" href={c.source_url} rel="noopener noreferrer" target="_blank">{c.title} ↗<span className="sr-only">, opens a new tab</span></a></blockquote>)}</div>}</div></article>)}</section>
 <p className="sr-only" role="status">{busy?'Skin Coach is reviewing your question.':messages.length?`${messages.length} answers in your conversation.`:''}</p>
 <form className="panel stack coach-composer" onSubmit={send}><label className="field">Your skincare question<textarea required maxLength={1800} value={message} disabled={busy} aria-describedby="coach-character-count" placeholder="What would you like to know about your skincare routine?" onChange={e=>setMessage(e.target.value)}/></label><span className="muted" id="coach-character-count">{message.length} / 1,800 characters</span><label className="check-label"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/>Allow the platform analysis service to process this message.</label>{error&&<p className="notice error" role="alert">{error}</p>}<button className="button primary" disabled={busy||!consent||!ready||state.loading||!!state.error||!message.trim()}>{busy?'Reviewing…':'Ask Skin Coach'}</button></form></AppFrame>;
}
