const assert=require('node:assert/strict');
const {createPortal}=require('../dist/portal/server');const {LocalStore}=require('../dist/portal/store');const {RETAILERS}=require('../dist/portal/retailers');
(async()=>{const db=new LocalStore(':memory:');let paymentCalls=0,assistantCalls=0;const stripe=new Proxy({}, {get(){paymentCalls++;throw Error('Payment SDK must not be used in referral mode');}});
 const coach={configured:true,answer:async()=>{assistantCalls++;return{kind:'reviewed_excerpts',text:'From the reviewed skincare library:',citations:[]};}};
 const app=await createPortal({store:db,stripe,coach,env:{NODE_ENV:'test',DEMO_MODE:'true',PUBLIC_ORIGIN:'http://localhost:3000'}});
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const origin='http://127.0.0.1:'+server.address().port;
 function client(){let cookie='',csrf='';return async(path,body,extra={})=>{const res=await fetch(origin+'/api/hub'+path,{method:body===undefined?'GET':'POST',headers:{cookie,origin:'http://localhost:3000','content-type':'application/json','x-csrf-token':csrf,...extra},body:body===undefined?undefined:JSON.stringify(body)});if(res.headers.get('set-cookie'))cookie=res.headers.get('set-cookie').split(';')[0];const data=await res.json();if(data.csrf)csrf=data.csrf;return{status:res.status,data};};}
 try{
 const a=client(),b=client();const session=await a('/session');await b('/session');assert.equal(session.status,200);assert.equal(session.data.commerce.mode,'external_referral');assert.equal(session.data.payments_configured,false);
 const onboard=await a('/assistant',{role:'onboarding',message:'How do I get started?'});assert.equal(onboard.status,200);assert.equal(onboard.data.kind,'guidance');assert.equal(onboard.data.next_step.path,'/skin-match');
 const generalOnboard=await a('/assistant',{role:'customer_care',message:'How do I get started?'});assert.equal(generalOnboard.status,200);assert.equal(generalOnboard.data.category,'onboarding');assert.equal(generalOnboard.data.next_step.path,'/skin-match');
 const payment=await a('/assistant',{role:'routine_guidance',message:'Was my retailer payment charged?'});assert.equal(payment.status,200);assert.equal(payment.data.kind,'handoff');assert.equal(payment.data.next_step.path,'/orders');assert.equal(assistantCalls,0);assert.equal(paymentCalls,0);
 const care=await a('/assistant',{role:'customer_care',message:'I need help with the portal'});assert.equal(care.status,200);assert.equal(care.data.next_step.path,'/support');assert.equal(assistantCalls,0);
 const medical=await a('/assistant',{role:'product_referral',message:'Can you diagnose this rash?'});assert.equal(medical.status,200);assert.equal(medical.data.category,'safety');assert.equal(assistantCalls,0);
 assert.equal((await a('/assistant/action',{action:'unknown',role:'onboarding',path:'/skin-match'})).status,400);
 assert.equal((await a('/assistant/action',{action:'next_step_opened',role:'unknown',path:'/skin-match'})).status,400);
 assert.equal((await a('/assistant/action',{action:'next_step_opened',role:'onboarding',path:'https://evil.example'})).status,400);
 assert.equal((await a('/assistant/action',{action:'next_step_opened',role:'onboarding',path:'/skin-match'})).status,200);
 assert.equal((await a('/assistant/action',{action:'next_step_opened',role:'customer_care',path:'/support'})).status,200);
 assert.equal((await a('/assistant',{role:'unknown',message:'Hello'})).status,400);
 assert.equal((await a('/assistant',{role:'routine_guidance',message:'What does a moisturizer do?',ai_consent:true})).status,401);
 const directory=(await a('/retailers')).data,retailers=directory.retailers;assert.equal(retailers.length,11);assert.deepEqual(new Set(retailers.map(r=>r.region)),new Set(['South Korea','US','EU']));
 assert.equal(new Set(retailers.map(r=>r.id)).size,retailers.length);
 assert.equal(directory.segments.length,7);
 for(const segment of directory.segments){assert(retailers.some(r=>r.segments.includes(segment.id)),segment.id+' has a destination');assert(segment.studio.startsWith('/'));}
 for(const retailer of retailers){assert(retailer.specialty);assert(retailer.segments.every(id=>directory.segments.some(s=>s.id===id)));assert.equal(new URL(retailer.source_url).protocol,'https:');}
 for(const r of retailers){const url=new URL(r.url);assert.equal(url.protocol,'https:');assert.equal(url.search,'');assert.equal(url.username,'');assert.equal(r.relationship,'independent');assert(RETAILERS.some(v=>v.id===r.id&&v.url===r.url));}
 assert.equal((await a('/retailers/outbound',{id:'not-listed',segment:'all'})).status,400);
 assert.equal((await a('/retailers/outbound',{id:retailers[0].id,segment:'not-a-segment'})).status,400);
 assert.equal((await a('/retailers/outbound',{id:retailers[0].id,segment:'all'})).status,200);
 assert.equal((await a('/retailers/outbound',{id:retailers[0].id,segment:retailers[0].segments[0]})).status,200);
 assert.equal((await a('/saved-retailers',{id:retailers[0].id,saved:true},{'x-csrf-token':'bad'})).status,403);
 assert.equal((await a('/saved-retailers',{id:retailers[0].id,saved:true},{origin:'https://wrong.example'})).status,403);
 assert.equal((await a('/saved-retailers',{id:'https://evil.example',saved:true})).status,400);
 await a('/saved-retailers',{id:retailers[0].id,saved:true});await a('/saved-retailers',{id:retailers[0].id,saved:true});
 assert.deepEqual((await a('/saved-retailers')).data.ids,[retailers[0].id]);assert.deepEqual((await b('/saved-retailers')).data.ids,[]);
 await a('/saved-retailers',{id:retailers[0].id,saved:false});assert.deepEqual((await a('/saved-retailers')).data.ids,[]);
 for(const id of ['mented','pattern','overtone','universal-standard','haute-hijab']){assert.equal((await a('/saved-retailers',{id,saved:true})).status,200);assert((await a('/saved-retailers')).data.ids.includes(id));assert.deepEqual((await b('/saved-retailers')).data.ids,[]);await a('/saved-retailers',{id,saved:false});}
 for(const path of ['/checkout','/cart','/cart/routine','/admin/payout','/admin/refund','/admin/fulfill','/partners/onboard','/admin/partner/approve','/membership/checkout','/membership/portal']){
  const response=await a(path,{});assert.equal(response.status,409,path);assert.equal(response.data.error.code,'external_commerce_only',path);
 }
 assert.equal((await a('/orders')).status,409);assert.equal((await fetch(origin+'/webhooks/stripe',{method:'POST'})).status,409);assert.equal(paymentCalls,0);
 const input={skin_type:'dry',concerns:['hydration'],sensitivity:'none',age_band:'26_35',current_routine:'basic',desired_outcome:'glow',budget_range:'between_25_50',ingredient_avoidances:[],consent:true};
 const result=await a('/profile',input);assert.equal(result.status,200,JSON.stringify(result));assert(result.data.profile.routine.steps.length>0);assert(result.data.profile.routine.steps.some(s=>s.slot==='sunscreen'&&s.time==='am'),'required sunscreen step should be present for the demo catalog');assert.equal((await b('/profile')).data.profile,null);
 const products=(await a('/catalog')).data.products;await a('/reminders',{product_id:products[0].id,days:30});assert.equal((await a('/reminders')).data.reminders.length,1);assert.equal((await b('/reminders')).data.reminders.length,0);
 await a('/reminders/remove',{product_id:products[0].id});assert.equal((await a('/reminders')).data.reminders.length,0);
 assert.equal((await a('/admin',undefined,{'x-admin-user-id':'superadmin'})).status,401);
 assert.equal((await a('/admin/ai-routing')).status,401);
 await db.tx(async r=>{const user={id:'operator_1',email:'operator@example.test',roles:['superadmin']};await r.put('accounts',user.id,user);for(const session of await r.entries('sessions'))await r.put('sessions',session.id,{...session.value,userId:user.id});await r.put('ai_routing_log','routing_probe',{task_type:'coach_answer',provider:'ollama',model:'llama3.2:3b',latency_ms:123,input_tokens:10,output_tokens:5,cost_cents:0,used_fallback:false,attempts:1,validation_failed:false,failure_reason:null,created_at:new Date().toISOString()});await r.put('ai_routing_log','routing_hosted',{task_type:'operator_analysis',provider:'openai',model:'gpt-6-astra',latency_ms:900,input_tokens:1000,output_tokens:500,cost_cents:3.5,used_fallback:true,attempts:2,validation_failed:true,failure_reason:'invalid_operator_analysis',created_at:new Date().toISOString()});await r.put('ai_budget','2026-09-14:operator_1:tier3_premium',{cents:7,updated_at:new Date().toISOString()});await r.put('ai_budget_reservations','hold_stale',{budget_key:'2026-09-14:operator_1:tier3_premium',reserved_cents:7,status:'reserved',created_at:new Date(Date.now()-660000).toISOString()});await r.put('deletion_requests','user_private_identity',{request_id:'request_public_reference',actor:'user_private_identity',user_id:'private_identity',requested_at:new Date(Date.now()-31*86400000).toISOString(),not_before:new Date(Date.now()-86400000).toISOString(),status:'pending',attempts:2,blocked_reasons:['active_consumer_subscription'],last_error:'private provider detail'});await r.put('deletion_completions','completed_public_reference',{request_id:'completed_public_reference',requested_at:new Date(Date.now()-35*86400000).toISOString(),completed_at:new Date(Date.now()-86400000).toISOString(),identity_provider:'supabase'});});
 assert.equal((await a('/assistant',{role:'routine_guidance',message:'What does a moisturizer do?',ai_consent:false})).status,400);assert.equal(assistantCalls,0);
 const reviewed=await a('/assistant',{role:'routine_guidance',message:'What does a moisturizer do?',ai_consent:true});assert.equal(reviewed.status,200);assert.equal(reviewed.data.kind,'reviewed_excerpts');assert.equal(reviewed.data.role,'routine_guidance');assert.equal(assistantCalls,1);
 assert.equal((await a('/account/deletion-request',{confirm:false})).status,400);
 const deletion=(await a('/account/deletion-request',{confirm:true})).data.request;assert.equal(deletion.status,'pending');assert.equal(deletion.user_id,'operator_1');assert(Date.parse(deletion.not_before)>Date.now()+29*86400000);
 const repeated=(await a('/account/deletion-request',{confirm:true})).data.request;assert.equal(repeated.request_id,deletion.request_id);assert.equal((await a('/session')).data.deletion_request.request_id,deletion.request_id);assert.equal((await a('/account/export')).data.deletion_request.request_id,deletion.request_id);
 assert.equal((await a('/account/deletion-cancel',{confirm:true})).status,200);assert.equal((await a('/account/deletion-request')).data.request,null);assert.equal((await a('/account/deletion-cancel',{confirm:true})).status,404);
 const outsider=client();await outsider('/session');assert.equal((await outsider('/admin/deletions')).status,401);const adminSnapshot=(await a('/admin')).data;assert.equal('deletion_requests' in adminSnapshot,false);
 const privacy=(await a('/admin/deletions')).data;assert.equal(privacy.summary.total,1);assert.equal(privacy.summary.due,1);assert.equal(privacy.summary.blocked,1);assert.equal(privacy.summary.completed_30_days,1);assert.equal(privacy.identity_deletion_configured,false);assert.deepEqual(privacy.queue[0].blocked_reasons,['active_consumer_subscription']);assert.equal(privacy.queue[0].service_error,true);assert.equal('identity_provider' in privacy.recent_completions[0],false);assert.equal(privacy.recent_completions[0].request_id,'completed_public_reference');const privacyText=JSON.stringify(privacy);assert(!privacyText.includes('user_private_identity'));assert(!privacyText.includes('private_identity'));assert(!privacyText.includes('private provider detail'));assert(!privacyText.includes('supabase'));
 const routing=await a('/admin/ai-routing');assert.equal(routing.status,200);assert.equal(routing.data.requests,2);assert(routing.data.routes.some(x=>x.route==='Guided answers'));assert(!JSON.stringify(routing.data).includes('ollama'));assert(!JSON.stringify(routing.data).includes('gpt-6-astra'));
 assert.equal((await a('/admin/backup/verified',{completed_at:new Date(Date.now()+3600000).toISOString(),location_identifier:'offsite-1',checksum:'sha256:future'})).status,400);
 assert.equal((await a('/admin/backup/verified',{completed_at:new Date(Date.now()-60000).toISOString(),location_identifier:'offsite-1',checksum:'sha256:verified'})).status,200);
 const economics=await a('/admin/ai-economics');assert.equal(economics.status,200);assert.equal(economics.data.totals.requests,2);assert.equal(economics.data.totals.failures,1);assert.equal(economics.data.totals.fallbacks,1);assert.equal(economics.data.totals.validation_failures,1);assert.equal(economics.data.totals.cost_cents,3.5);assert.equal(economics.data.pending_reservations,1);assert.equal(economics.data.stale_reservations,1);assert(economics.data.alerts.some(x=>x.includes('validation')));assert.equal(economics.data.by_route.find(x=>x.route==='Complex review').requests,1);assert(!JSON.stringify(economics.data).includes('openai'));assert(!JSON.stringify(economics.data).includes('gpt-6-astra'));
 const catalogHealth=await a('/admin/catalog-health');assert.equal(catalogHealth.status,200);assert.equal(catalogHealth.data.mode,'demo');assert.equal(catalogHealth.data.products.total,9);assert.equal(catalogHealth.data.products.active,9);assert.equal(catalogHealth.data.slot_coverage.find(x=>x.slot==='sunscreen').active,1);assert(catalogHealth.data.warnings.some(x=>x.includes('sample-only')));assert(catalogHealth.data.note.includes('metadata-only'));
 assert.equal((await a('/support',{subject:'Bad category',message:'Test request',request_type:'medical_diagnosis'})).status,400);
 assert.equal((await a('/support',{subject:'Bad source',message:'Test request',source:'advertising_pixel'})).status,400);
 const savedRequest=await a('/support',{id:'client-chosen-id',subject:'Portal question',message:'Test request',request_type:'onboarding',source:'guided_handoff'});
 assert.equal(savedRequest.status,200);assert.equal(savedRequest.data.saved,true);assert.match(savedRequest.data.request.id,/^[0-9a-f-]{36}$/);assert.notEqual(savedRequest.data.request.id,'client-chosen-id');assert.equal(savedRequest.data.request.status,'open');assert.equal(savedRequest.data.request.request_type,'onboarding');assert(!Number.isNaN(Date.parse(savedRequest.data.request.created_at)));
 const ownerTicket=(await a('/support')).data.tickets.find(t=>t.id===savedRequest.data.request.id);assert(ownerTicket);assert.equal(ownerTicket.created_at,savedRequest.data.request.created_at);assert.equal(ownerTicket.request_type,'onboarding');assert.equal('actor' in ownerTicket,false);assert.equal('email' in ownerTicket,false);assert.equal('assigned_to' in ownerTicket,false);assert.equal('source' in ownerTicket,false);
 assert((await a('/admin')).data.tickets.some(t=>t.id===savedRequest.data.request.id),'operator shares the customer reference');assert.equal((await b('/support')).data.tickets.length,0);
 assert.equal((await a('/admin/ticket',{id:savedRequest.data.request.id,status:'waiting_customer',reply:''})).status,400);
 assert.equal((await a('/admin/ticket',{id:savedRequest.data.request.id,status:'in_review',reply:''})).status,200);
 assert.equal((await a('/support')).data.tickets.find(t=>t.id===savedRequest.data.request.id).status,'in_review');
 assert.equal((await a('/admin/ticket',{id:savedRequest.data.request.id,status:'waiting_customer',reply:'Please confirm which portal page you were using.'})).status,200);
 const waitingTicket=(await a('/support')).data.tickets.find(t=>t.id===savedRequest.data.request.id);assert.equal(waitingTicket.status,'waiting_customer');assert.equal(waitingTicket.replies.length,1);assert.equal(waitingTicket.replies[0].text,'Please confirm which portal page you were using.');assert.equal('assigned_to' in waitingTicket,false);
 const exportedTicket=(await a('/account/export')).data.tickets.find(t=>t.id===savedRequest.data.request.id);assert(exportedTicket);assert.equal('assigned_to' in exportedTicket,false);assert.equal('source' in exportedTicket,false);assert.equal('actor' in exportedTicket,false);assert.equal('email' in exportedTicket,false);
 const supportMetrics=await a('/admin/support-metrics');assert.equal(supportMetrics.status,200);assert(supportMetrics.data.events.guidance_requested>=4);assert.equal(supportMetrics.data.events.guidance_result,6);assert.equal(supportMetrics.data.events.next_step_opened,2);assert.equal(supportMetrics.data.events.request_saved,1);assert.equal(supportMetrics.data.events.operator_updated,2);assert.equal(supportMetrics.data.request_types.onboarding,1);assert(supportMetrics.data.guidance_by_role.some(row=>row.role==='onboarding'&&row.requests>=1));assert(supportMetrics.data.guidance_outcomes.some(row=>row.role==='customer_care'&&row.kind==='handoff'&&row.category==='portal_support'));assert(supportMetrics.data.next_steps.some(row=>row.role==='onboarding'&&row.path==='/skin-match'&&row.count===1));assert.deepEqual(supportMetrics.data.handoff_funnel,{offered:1,support_opened:1,request_saved:1});const metricsText=JSON.stringify(supportMetrics.data);assert(!metricsText.includes('Test request'));assert(!metricsText.includes('operator@example.test'));assert(!metricsText.includes('operator_1'));
 const referralMetrics=await a('/admin/referral-metrics');assert.equal(referralMetrics.status,200);assert.equal(referralMetrics.data.summary.outbound,2);assert.equal(referralMetrics.data.summary.saved,6);assert.equal(referralMetrics.data.summary.unsaved,6);assert.equal(referralMetrics.data.commercial_agreements,'pending');assert(referralMetrics.data.interpretation.includes('not unique customers'));const referralText=JSON.stringify(referralMetrics.data);assert(!referralText.includes('operator@example.test'));assert(!referralText.includes('operator_1'));assert(!referralText.includes('Test request'));
 await assert.rejects(db.tx(async r=>{await r.put('probe','rollback',{value:1});throw Error('rollback');}));assert.equal(await db.tx(r=>r.get('probe','rollback')),undefined);
 console.log('Referral portal checks passed: destination allowlist, saved-list isolation, CSRF/origin, all legacy commerce blocked without payment calls, profiles, reminders, support and rollback.');
 }finally{await new Promise(r=>server.close(r));await db.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
